FROM node:20-alpine
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_OPTIONS="--max-old-space-size=4096"

COPY package*.json ./
RUN npm ci

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_MOCK_ENV

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_MOCK_ENV=$NEXT_PUBLIC_MOCK_ENV

COPY . .

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]